name: Azure AD OAuth Application Consent Granted By User
id: 10ec9031-015b-4617-b453-c0c1ab729007
version: 1
date: '2023-10-27'
author: Mauricio Velazco, Splunk
status: production
type: TTP
data_source:
- UPDATE_DATA_SOURCE
description: UPDATE_DESCRIPTION
search: >
  `azure_monitor_aad` operationName="Consent to application" properties.result=success
  | rename properties.* as * 
  | eval permissions_index = if(mvfind('targetResources{}.modifiedProperties{}.displayName', "ConsentAction.Permissions") >= 0, mvfind('targetResources{}.modifiedProperties{}.displayName', "ConsentAction.Permissions"), -1)
  | eval permissions = mvindex('targetResources{}.modifiedProperties{}.newValue',permissions_index)
  | rex field=permissions "Scope: (?<Scope>[^,]+)"
  | stats count min(_time) as firstTime max(_time) as lastTime by operationName, user, Scope
  | `security_content_ctime(firstTime)`
  | `security_content_ctime(lastTime)`
  | `azure_ad_oauth_application_consent_granted_by_user_filter`
how_to_implement: You must install the latest version of Splunk Add-on for Microsoft
  Cloud Services from Splunkbase (https://splunkbase.splunk.com/app/3110/#/details). You must be ingesting Azure Active Directory events into your Splunk environment through an EventHub.
  This analytic was written to be used with the azure:monitor:aad sourcetype leveraging the AuditLog log category.
known_false_positives: UPDATE_KNOWN_FALSE_POSITIVES
references:
- REFERENCE
tags:
  analytic_story:
  - UPDATE_STORY_NAME
  asset_type: Azure AD
  confidence: 60
  impact: 60
  message: UPDATE message
  mitre_attack_id:
  - T1003.002
  observable:
  - name: user
    type: User
    role:
    - Victim
  product:
  - Splunk Enterprise
  - Splunk Enterprise Security
  - Splunk Cloud
  risk_score: 36
  required_fields:
  - UPDATE_required_fields
  security_domain: identity
tests:
- name: True Positive Test
  attack_data:
  - data: https://media.githubusercontent.com/media/splunk/attack_data/master/datasets/attack_techniques/T1528/azure_ad_user_consent_granted/azure_ad_user_consent_granted.log
    source: Azure AD
    sourcetype: azure:monitor:aad

