name: O365 Mailbox Read Access Granted to Application
id: 27ab61c5-f08a-438a-b4d3-325e666490b3
version: 1
date: '2023-09-01'
author: Mauricio Velazco, Splunk
status: production
type: TTP
data_source:
- UPDATE_DATA_SOURCE
description: UPDATE_DESCRIPTION
search: '| UPDATE_SPL | `o365_mailbox_read_access_granted_to_application_filter`'
how_to_implement: UPDATE_HOW_TO_IMPLEMENT
known_false_positives: UPDATE_KNOWN_FALSE_POSITIVES
references:
- REFERENCE
tags:
  analytic_story:
  - UPDATE_STORY_NAME
  asset_type: UPDATE asset_type
  atomic_guid:
  - UPDATE atomic_guid
  confidence: UPDATE value between 1-100
  impact: UPDATE value between 1-100
  message: UPDATE message
  mitre_attack_id:
  - T1003.002
  observable:
  - name: UPDATE
    type: UPDATE
    role:
    - UPDATE
  product:
  - Splunk Enterprise
  - Splunk Enterprise Security
  - Splunk Cloud
  risk_score: UPDATE (impact * confidence)/100
  required_fields:
  - UPDATE_required_fields
  security_domain: access
tests:
- name: True Positive Test
  attack_data:
  - data: UPDATE url to dataset
    source: UPDATE source
    sourcetype: UPDATE sourcetype
