name: O365 User Consent Denied for OAuth Application
id: 2d8679ef-b075-46be-8059-c25116cb1072
version: 1
date: '2023-10-12'
author: Mauricio Velazco, Splunk
status: production
type: TTP
data_source: []
description: UPDATE_DESCRIPTION
search: ' `o365_graph` status.errorCode=65004
  | rename userPrincipalName as user 
  | rename ipAddress as src_ip
  | stats max(_time) as lastTime by user src_ip appDisplayName status.failureReason
  | `security_content_ctime(lastTime)`
  | `o365_user_consent_denied_for_oauth_application_filter`'
how_to_implement: UPDATE_HOW_TO_IMPLEMENT
known_false_positives: UPDATE_KNOWN_FALSE_POSITIVES
references:
- REFERENCE
tags:
  analytic_story:
  - UPDATE_STORY_NAME
  asset_type: O365 tenant
  confidence: 100
  impact: 30
  message: UPDATE message
  mitre_attack_id:
  - T1003.002
  observable:
  - name: user
    type: User
    role:
    - Victim
  product:
  - Splunk Enterprise
  - Splunk Enterprise Security
  - Splunk Cloud
  risk_score: 30
  required_fields:
  - _time
  - status.errorCode
  - userPrincipalName
  - ipAddress
  - status.failureReason
  security_domain: identity
tests:
- name: True Positive Test
  attack_data:
  - data: https://media.githubusercontent.com/media/splunk/attack_data/master/datasets/attack_techniques/T1528/o365_user_consent_declined/o365_user_consent_declined.log
    source: o365
    sourcetype: o365:graph:api
