name: O365 Mail Permissioned Application Consent Granted by User
id: fddad083-cdf5-419d-83c6-baa85e329595
version: 1
date: '2023-10-12'
author: Mauricio Velazco, Splunk
status: production
type: TTP
data_source:
- UPDATE_DATA_SOURCE
description: UPDATE_DESCRIPTION
search: >
  `o365_management_activity` Workload=AzureActiveDirectory Operation="Consent to application." ResultStatus=Success
  | eval admin_consent =mvindex('ModifiedProperties{}.NewValue', 0)
  | search admin_consent=False
  | eval permissions =mvindex('ModifiedProperties{}.NewValue', 4)
  | rex field=permissions "Scope: (?<Scope>[^,]+)"
  | makemv delim=" " Scope
  | search Scope IN ("Mail.Read", "Mail.ReadBasic", "Mail.ReadWrite", "Mail.Read.Shared", "Mail.ReadWrite.Shared", "Mail.Send", "Mail.Send.Shared")
  | stats max(_time) as lastTime values(Scope) by Operation, user, object, ObjectId
  | `security_content_ctime(lastTime)`
  | `o365_mail_permissioned_application_consent_granted_by_user_filter`
how_to_implement: UPDATE_HOW_TO_IMPLEMENT
known_false_positives: UPDATE_KNOWN_FALSE_POSITIVES
references:
- REFERENCE
tags:
  analytic_story:
  - UPDATE_STORY_NAME
  asset_type: UPDATE asset_type
  atomic_guid:
  - UPDATE atomic_guid
  confidence: 50
  impact: 80
  message: UPDATE message
  mitre_attack_id:
  - T1003.002
  observable:
  - name: user
    type: User
    role:
    - Victim
  product:
  - Splunk Enterprise
  - Splunk Enterprise Security
  - Splunk Cloud
  risk_score: 40
  required_fields:
  - UPDATE_required_fields
  security_domain: identity
tests:
- name: True Positive Test
  attack_data:
  - data: https://media.githubusercontent.com/media/splunk/attack_data/master/datasets/attack_techniques/T1528/o365_user_consent_mail_permissions/o365_user_consent_mail_permissions.log
    source: o365
    sourcetype: o365:management:activity

