name: O365 ApplicationImpersonation Role Assigned
id: 49cdce75-f814-4d56-a7a4-c64ec3a481f2
version: 1
date: '2023-10-17'
author: Mauricio Velazco, Splunk
status: production
type: TTP
data_source: []
description: UPDATE_DESCRIPTION
search: '`o365_management_activity` Workload=Exchange Operation="New-ManagementRoleAssignment"  Role=ApplicationImpersonation
  | stats  max(_time) as lastTime by Operation, user, object, ObjectId, Role
  | `security_content_ctime(lastTime)`
  | `o365_applicationimpersonation_role_assigned_filter`'
how_to_implement: UPDATE_HOW_TO_IMPLEMENT
known_false_positives: UPDATE_KNOWN_FALSE_POSITIVES
references:
- https://attack.mitre.org/techniques/T1098/002/
- https://www.mandiant.com/resources/blog/remediation-and-hardening-strategies-for-microsoft-365-to-defend-against-unc2452
- https://www.mandiant.com/media/17656
tags:
  analytic_story:
  - UPDATE_STORY_NAME
  asset_type: Office 365 
  atomic_guid:
  - UPDATE atomic_guid
  confidence: 70
  impact: 80
  message: UPDATE message
  mitre_attack_id:
  - T1098
  - T1098.002
  observable:
  - name: user
    type: User
    role:
    - Attacker
  product:
  - Splunk Enterprise
  - Splunk Enterprise Security
  - Splunk Cloud
  risk_score: 56
  required_fields:
  - UPDATE_required_fields
  security_domain: audit
tests:
- name: True Positive Test
  attack_data:
  - data: https://media.githubusercontent.com/media/splunk/attack_data/master/datasets/attack_techniques/T1528/application_impersonation_role_assigned/application_impersonation_role_assigned.log
    source: O365
    sourcetype: o365:management:activity
