name: O365 Mailbox Read Access Granted to Application
id: 27ab61c5-f08a-438a-b4d3-325e666490b3
version: 1
date: '2023-09-01'
author: Mauricio Velazco, Splunk
status: production
type: TTP
data_source: []
description: The following analytic identifies instances where Mail.Read Graph API permissions are granted to an application registration within an Office 365
 tenant. This behavior could be indicative of an attacker who has gained privileged access to the tenant and is attempting to read mailboxes by exploiting 
 a new or existing application registration. Cyber defenders should investigate each occurrence of this sensitive permission being granted, as it
 could allow attackers to gain access to the email accounts of the entire organization.
search: '`o365_management_activity` Operation="Update application."
  | eval json_data=mvindex('ModifiedProperties{}.NewValue', 0)
  | eval json_data=replace(json_data, "^\[\s*", "")
  | eval json_data=replace(json_data, "\s*\]$", "")
  | spath input=json_data path=RequiredAppPermissions{}.EntitlementId output=EntitlementIds
  | eval match_found=mvfind(EntitlementIds, "810c84a8-4a9e-49e6-bf7d-12d183f40d01")
  | where isnotnull(match_found)
  | stats max(_time) as lastTime values(EntitlementIds) as EntitlementIds by Operation, UserId, object
  | `security_content_ctime(lastTime)`
  | `o365_mailbox_read_access_granted_to_application_filter`'
how_to_implement: You must install the Splunk Microsoft Office 365 Add-on.
known_false_positives: There are legitimate scenarios in wich an Application registrations requires Mailbox read access. Filter as needed.
references:
- REFERENCE
- https://learn.microsoft.com/en-us/graph/permissions-reference
tags:
  analytic_story:
  - UPDATE_STORY_NAME
  asset_type: Office 365 tenant
  confidence: 50
  impact: 90
  message: Application registration $object$ was grandes mailbox read access by $UserId$
  mitre_attack_id:
  - T1114.002
  - T1114
  observable:
  - name: UserId
    type: User
    role:
    - Attacker
  product:
  - Splunk Enterprise
  - Splunk Enterprise Security
  - Splunk Cloud
  risk_score: 45
  required_fields:
  - Operation
  - _time
  - ModifiedProperties{}.NewValue
  security_domain: access
tests:
- name: True Positive Test
  attack_data:
  - data: UPDATE url to dataset
    source: UPDATE source
    sourcetype: UPDATE sourcetype
