default:
  image: docker-hub.repo.splunkdev.net/python:3.9

variables:
  SKIP_DOWNSTREAM_TESTING:
    value: "False"
    description: "If true, downstream testing will be suppressed (useful for debugging or forcing a release in an emergency)."

stages:
  - validate
  - generate
  - app_inspect
  - test
  - release

include:
  - local: "pipeline/.validate.yml"
  - local: "pipeline/.generate.yml"
  - local: "pipeline/.test.yml"
  - local: "pipeline/.app_inspect.yml"
  - local: "pipeline/.release.yml"
  - local: "pipeline/.post.yml"

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_BRANCH =~ /^release_v[0-9]+\.[0-9]+\.[0-9]+$/
