name: Disabling CMD Application
id: ff86077c-9212-11eb-a1e6-acde48001122
version: 2
date: '2022-01-27'
author: Teoderick Contreras, Splunk
status: production
type: TTP
description: this search is to identify modification in registry to disable cmd prompt
  application. This technique is commonly seen in RAT, Trojan or WORM to prevent triaging
  or deleting there samples through cmd application which is one of the tool of analyst
  to traverse on directory and files.
data_source:
- Sysmon Event ID 13
search:
  selection1:
    Details: '0x00000001'
    TargetObject: '*\\SOFTWARE\\Policies\\Microsoft\\Windows\\System\\DisableCMD'
  condition: selection1
how_to_implement: To successfully implement this search you need to be ingesting information
  on process that include the name of the process responsible for the changes from
  your endpoints into the `Endpoint` datamodel in the `Registry` node. Also make sure
  that this registry was included in your config files ex. sysmon config to be monitored.
known_false_positives: admin may disable this application for non technical user.
references:
- https://any.run/report/ea4ea08407d4ee72e009103a3b77e5a09412b722fdef67315ea63f22011152af/a866d7b1-c236-4f26-a391-5ae32213dfc4#registry
tags:
  analytic_story:
  - Windows Defense Evasion Tactics
  - Windows Registry Abuse
  asset_type: Endpoint
  confidence: 50
  impact: 50
  message: The Windows command prompt was disabled on $dest$ by $user$.
  mitre_attack_id:
  - T1562.001
  - T1562
  observable:
  - name: user
    type: User
    role:
    - Victim
  - name: dest
    type: Hostname
    role:
    - Victim
  product:
  - Splunk Enterprise
  - Splunk Enterprise Security
  - Splunk Cloud
  risk_score: 25
  security_domain: endpoint
tests:
- name: True Positive Test
  attack_data:
  - data: https://media.githubusercontent.com/media/splunk/attack_data/master/datasets/attack_techniques/T1562.001/win_app_defender_disabling/windows-security.log
    source: WinEventLog:Security
    sourcetype: WinEventLog
    update_timestamp: true
  - data: https://media.githubusercontent.com/media/splunk/attack_data/master/datasets/attack_techniques/T1562.001/win_app_defender_disabling/windows-system.log
    source: WinEventLog:System
    sourcetype: WinEventLog
    update_timestamp: true
  - data: https://media.githubusercontent.com/media/splunk/attack_data/master/datasets/attack_techniques/T1562.001/win_app_defender_disabling/windows-sysmon.log
    source: XmlWinEventLog:Microsoft-Windows-Sysmon/Operational
    sourcetype: xmlwineventlog
