name: Linux Possible Append Command To At Allow Config File
id: 7bc20606-5f40-11ec-a586-acde48001122
version: 2
date: '2022-05-26'
author: Teoderick Contreras, Splunk
status: production
type: Anomaly
description: This analytic looks for suspicious commandline that may use to append
  user entry to /etc/at.allow or /etc/at.deny. These 2 files are commonly abused by
  malware, adversaries or red teamers to persist on the targeted or compromised host.
  These config file can restrict user that can only execute at application (another
  schedule task application in linux). attacker can create a user or add the compromised
  username to that config file to execute at to schedule it malicious code. This anomaly
  detection can be a good indicator to investigate further the entry in created config
  file and who created it to verify if it is a false positive.
data_source:
- Sysmon Event ID 1
search:
  selection1:
    CommandLine:
    - '*/etc/at.allow'
    - '*/etc/at.deny'
  selection2:
    CommandLine: '*echo*'
  condition: selection1 and selection2
how_to_implement: To successfully implement this search, you need to be ingesting
  logs with the process name, parent process, and command-line executions from your
  endpoints. If you are using Sysmon, you can use the Add-on for Linux Sysmon from
  Splunkbase.
known_false_positives: Administrator or network operator can use this commandline
  for automation purposes. Please update the filter macros to remove false positives.
references:
- https://linuxize.com/post/at-command-in-linux/
- https://attack.mitre.org/techniques/T1053/001/
tags:
  analytic_story:
  - Linux Privilege Escalation
  - Linux Persistence Techniques
  asset_type: Endpoint
  confidence: 30
  impact: 30
  message: A commandline $process$ that may modify at allow config file in $dest$
  mitre_attack_id:
  - T1053.002
  - T1053
  observable:
  - name: dest
    type: Hostname
    role:
    - Victim
  product:
  - Splunk Enterprise
  - Splunk Enterprise Security
  - Splunk Cloud
  risk_score: 9
  security_domain: endpoint
tests:
- name: True Positive Test
  attack_data:
  - data: https://media.githubusercontent.com/media/splunk/attack_data/master/datasets/attack_techniques/T1053.002/at_execution/sysmon_linux.log
    source: Syslog:Linux-Sysmon/Operational
    sourcetype: sysmon_linux
