name: Windows System Network Config Discovery Display DNS
id: e24f0a0e-41a9-419f-9999-eacab15efc36
version: 1
date: '2022-11-30'
author: Teoderick Contreras, Splunk
status: production
type: Hunting
description: The following analytic identifies a process command line that retrieves
  dns reply information using Windows OS built-in tool IPConfig. This technique is
  being abused by threat actors, adversaries and post exploitation tools like WINPEAS
  to retrieve DNS information for the targeted host. This IPConfig parameter (/displaydns)
  can show dns server resource record, record name, record type, time to live data
  length and dns reply. This hunting detection can be a good pivot to check which
  process is executing this command line in specific host system that may lead to
  malware or adversaries gathering network information.
data_source:
- Sysmon Event ID 1
search:
  selection1:
    CommandLine: '*/displaydns*'
    OriginalFileName: ipconfig.exe
  selection2:
    Image|endswith: ipconfig.exe
  condition: selection1 or selection2
how_to_implement: To successfully implement this search, you need to be ingesting
  logs with the process name, parent process, and command-line executions from your
  endpoints. If you are using Sysmon, you must have at least version 6.0.4 of the
  Sysmon TA. Tune and filter known instances of wermgr.exe may be used.
known_false_positives: unknown
references:
- https://superuser.com/questions/230308/explain-output-of-ipconfig-displaydns
- https://github.com/carlospolop/PEASS-ng/tree/master/winPEAS
- https://www.microsoft.com/en-us/security/blog/2022/10/14/new-prestige-ransomware-impacts-organizations-in-ukraine-and-poland/
tags:
  analytic_story:
  - Windows Post-Exploitation
  - Prestige Ransomware
  asset_type: Endpoint
  confidence: 30
  impact: 30
  message: process $process_name$ with commandline $process$ is executed in $dest$
  mitre_attack_id:
  - T1016
  observable:
  - name: dest
    type: Hostname
    role:
    - Victim
  product:
  - Splunk Enterprise
  - Splunk Enterprise Security
  - Splunk Cloud
  risk_score: 9
  security_domain: endpoint
tests:
- name: True Positive Test
  attack_data:
  - data: https://media.githubusercontent.com/media/splunk/attack_data/master/datasets/malware/winpeas/sysmon.log
    source: XmlWinEventLog:Microsoft-Windows-Sysmon/Operational
    sourcetype: xmlwineventlog
    update_timestamp: true
