name: auto-update
on:
  push:
    branches:
      - develop
jobs:                       
  autoupdate:
    name: autoupdate
    runs-on: ubuntu-latest
    steps:
      - uses: docker://chinthakagodawita/autoupdate-action:v1
        env:
          GITHUB_TOKEN: "${{ secrets.SECURITY_CONTENT_ADMIN_TASKS }}"
          DRY_RUN: "false"
          MERGE_MSG: "Branch was auto-updated."
