name: Initial contentctl test workflow

# Trigger the workflow on pull request
on:
    push:
    pull_request:
      types: [opened, reopened]

jobs:
  contentctl_test:
    name: run contentctl test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9' #Available versions here - https://github.com/actions/python-versions/releases  easy to change/make a matrix/use pypy
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
      
      - name: Everything
        run: |
            git clone https://github.com/splunk/contentctl
            cd contentctl 
            git checkout diff_test_cli_support
            git pull
            python -m pip install poetry
            poetry install
            poetry run contentctl -p ../ validate
            poetry run contentctl -p ../ test --mode changes --target_branch develop --test_branch TR_3232_azure_ad
