name: datasource-ta-check
on:
  pull_request_target:
  push:
    branches:
      - develop

jobs:
  datasource-ta-check: 
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Check out the repository code
        uses: actions/checkout@v4
       
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          architecture: 'x64'
     
      - name: Install Python Dependencies and contentctl 
        run: |
          pip install contentctl>=4.0.0
          
      - name: Run datasource TA check
        run: |
          contentctl validate --data-source-TA-validation