name: validate-and-build
on:
  push:
  pull_request:
    types: [opened, reopened]
jobs:

  validate-and-build:
    #Note that the CircleCI job used a Container.  The way to do this with Github Actions
    #is to first start up a Virtual Machine, then we can by following:
    # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idcontainer
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository code
        uses: actions/checkout@v3
       
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9' #Available versions here - https://github.com/actions/python-versions/releases  easy to change/make a matrix/use pypy
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified

      - name: Install System Packages
        run: |
          sudo apt update -qq
          sudo apt install jq -qq
      

      - name: Install Python Dependencies and ContentCTL
        run: |
          python3.9 -m venv .venv
          source .venv/bin/activate
          pip install contentctl==3.4.2
      
      - name: content_ctl validate
        run: |
          contentctl --enable_enrichment validate
  

      - name: contentctl generate
        run: |
          contentctl --enable_enrichment build
          mkdir artifacts
          mv dist/DA-ESS-ContentUpdate-latest.tar.gz artifacts/

      - name: store_artifacts
        uses: actions/upload-artifact@v3
        with:
          name: content-latest
          path: |
            artifacts/DA-ESS-ContentUpdate-latest.tar.gz